IMAGE_FOLDER: "/Volumes/T7/NA/downloaded_photos"
ANNOTATION_FOLDER: "/Volumes/T7/NA/dutch_archives_analysis"
IMAGE_SIZE: 224
BATCH_SIZE: 32
MEAN: [0.485, 0.456, 0.406]
STD: [0.229, 0.224, 0.225]
SEED: 42

TEXT-GENERATION:
  GLOBAL:
    TEMPERATURE: 0.0
    TOP_P: 1.0
    TOP_K: 100
    MAX_NEW_TOKENS: 128
