IMAGE_FOLDER: "/data/data_fxu/DutchArchive/images"
ANNOTATION_FOLDER: "/data/data_fxu/DutchArchive/annotations"
IMAGE_SIZE: 224
BATCH_SIZE: 32
MEAN: [0.485, 0.456, 0.406]
STD: [0.229, 0.224, 0.225]
SEED: 42
DEVICE: 0

TEXT-GENERATION:
  GLOBAL:
    TEMPERATURE: 0.1
    TOP_P: 0.9
    TOP_K: 50
    MAX_NEW_TOKENS: 128
